### ISSUE TITLE
Add warnings for 2 tricky problems I had.

### ISSUE THREAD

**Issue by GiitHuub** [rubberduck203/stm32f3-discovery#32]
I had 2 problems with the examples which required non-obvious fixes.
1. To make OpenOCD work under Windows 10, I had to use a USB 2.0 port, not a USB 3.1 port. 
1. To make ITM output work ,I had to solder over the SB10 solder bridge on the Discovery board.

**Comment by rubberduck203** [comment]
The prior almost sounds like an issue with OpenOCD. Have you submitted an issue there?

Another thought, maybe submit a PR to add a note to the [Embedded Rust Book](https://rust-embedded.github.io/book/start/hardware.html)? 

As for the later, I could have sworn there was a section on ITM in the [Discovery Book](https://rust-embedded.github.io/discovery/index.html), but I guess not. I’m sure a PR adding some content for ITM would be well received. 

I kind of have been taking an approach of offloading these kinds of things to other sources of info about the hardware, but I would accept a PR here that updates the README. Thanks for sharing the feedback.

**Comment by GiitHuub** [comment]
I am having more issues with getting the samples to run. Looking into ITM / STM32F3Discovery / OpenOCD / Win10 integration with stm32f3-discovery / Cortex-Debug interests me.  Just mark this as closed, and hopefully I can do a comprehensive PR later. 
+

**Comment by rubberduck203** [comment]
Sure thing. Feel free to respond to this issue if you get stuck.
