### ISSUE TITLE
Example for using SPI

### ISSUE THREAD

**Issue by WyseNynja** [rubberduck203/stm32f3-discovery#34]
Hello! I'm wondering if you have an example of how to setup SPI.

The feather_m0 board that I've used previously has a helper for setting up the master. Maybe something similar could be added here. https://docs.rs/feather_m0/0.6.1/feather_m0/fn.spi_master.html

**Comment by WyseNynja** [comment]
I found an example.

https://docs.rs/crate/stm32f3xx-hal/0.4.3/source/examples/spi.rs

**Comment by rubberduck203** [comment]
I’m sorry I couldn’t respond sooner. I was on my yearly off-grid camping trip. I’m glad you were able to find what you needed.
