### ISSUE TITLE
Allow LED access via compass direction

### ISSUE THREAD

**Issue by rubberduck203** [rubberduck203/stm32f3-discovery#9]
Currently, the led abstraction allows access via their names (`ld3`, etc).
The board is also labeled with directions.
Allow users to access the Leds via the direction, North, South, East, West, etc.

Related: #4, #8.

**Comment by sirhcel** [comment]
What about a direction enum and mutably borrowing from `Leds` like in https://github.com/sirhcel/stm32f3-discovery/commit/06692b6867ce49aee9cae95e7482638a6fc3342b? I'm commenting in the first place as a PR without having #38 landed would look pretty cluttered up.

**Comment by rubberduck203** [comment]
That looks that a reasonable approach to me.

**Comment by sirhcel** [comment]
Alright. Then I prepared #39.

**Comment by rubberduck203** [comment]
#39 added a method for accessing the leds via the direction printed on the board.
Before releasing:

- [ ] Split the `roulette` example into three. 
  * `into_array` indexing
  * `into_array` iterator
  * `for_direction`
- There should be an easy way to get an array or iterator of directions
- Make sure we understand the consequences of the mutable borrowing of a single struct field

**Comment by rubberduck203** [comment]
@sirhcel would you mind taking a look at #40 and letting me know what you think?

**Comment by rubberduck203** [comment]
#41 introduces the Iterator I’ve been wanting to expose. Now I just need to decide if it’s actually a good idea to deprecate `into_array()` or if I should just add a note to the docs strongly recommending `iter_mut()` instead.

**Comment by rubberduck203** [comment]
0.7.1 is now available on crates.io
Docs are in the queue now and should be available soon.

I apologize that I didn't think about adding a note about your contribution until after I published the crate, but it is in the changelog in the readme.

Thanks for the help!

**Comment by sirhcel** [comment]
> #41 introduces the Iterator I’ve been wanting to expose. Now I just need to decide if it’s actually a good idea to deprecate `into_array()` or if I should just add a note to the docs strongly recommending `iter_mut()` instead.

This is awesome! Thank you! I was thinking about how this could be implemented and I'm impressed from #41. This is a bit out of reach for my actual skills.

> I apologize that I didn't think about adding a note about your contribution until after I published the crate, but it is in the changelog in the readme.

No worries. Isn't this for the spirit and not for the fame? It was a pleasure to help you out with my first iterator ever implemented in Rust. :)

**Comment by rubberduck203** [comment]
Lol. It was beyond my skills until I did it!
